packages:
  - "api/*"
  - "ui/*"
  - "packages/*"
  - tests

catalog:
  "@biomejs/biome": ^1.9.4
  "@playwright/test": ^1.51.1
  "@types/node": ^22.14.0
  "@swc/cli": "^0.6.0"
  "@swc/core": "^1.11.16"
  "typescript": "^5.8.2"
  "tsx": "^4.19.3"
  "ulid": "^3.0.0"
